#!/usr/bin/env php
<?php

define('TMPROOT', realpath(__DIR__ .'/../').DIRECTORY_SEPARATOR);

//check if this is command line and install
global $argv, $argc;

if(isset($argv)) {
	if(!isset($argv[1])) {
		echo "Install Cumula Usage: install <name>\n";
		exit;
	}
	include TMPROOT.'bin'.DIRECTORY_SEPARATOR.'install.php';
}

include TMPROOT.'bin'.DIRECTORY_SEPARATOR.'boot.php';